apiVersion: v1
data:
  frontend.conf: |
    # This is the backend application we are protecting with OpenID Connect
    upstream my_backend {
        zone my_backend 64k;
        server your-app.project.svc.cluster.local:8080;
    }

    # Custom log format to include the 'sub' claim in the REMOTE_USER field
    log_format main_jwt '$remote_addr - $jwt_claim_sub [$time_local] "$request" $status '
                        '$body_bytes_sent "$http_referer" "$http_user_agent" "$http_x_forwarded_for"';

    # The frontend server - reverse proxy with OpenID Connect authentication
    #
    server {
        include conf.d/openid_connect.server_conf; # Authorization code flow and Relying Party processing
        error_log /var/log/nginx/error.log debug;  # Reduce severity level as required

        listen 8010; # Use SSL/TLS in production

        set $oidc_authz_endpoint "https://<oidc_server>:8443/auth/realms/master/protocol/openid-connect/auth";
        set $oidc_token_endpoint "https://<oidc_server>:8443/auth/realms/master/protocol/openid-connect/token";
        set $oidc_client "<your_client>";
        set $oidc_client_secret "<your_secret>";
        set $oidc_hmac_key "ChangeMe";
        set $oidc_jwt_keyfile "https://<oidc_server>:8443/auth/realms/master/protocol/openid-connect/certs";

        location / {
            # This site is protected with OpenID Connect
            auth_jwt "" token=$session_jwt;
            error_page 401 = @do_oidc_flow;

            #auth_jwt_key_file $oidc_jwt_keyfile; # Enable when using filename
            auth_jwt_key_request /_jwks_uri; # Enable when using URL

            # Successfully authenticated users are proxied to the backend,
            # with 'sub' claim passed as HTTP header
            proxy_set_header id $jwt_claim_sub;
            proxy_set_header full_name $jwt_claim_name;
            proxy_set_header username $jwt_claim_preferred_username;
            proxy_set_header email $jwt_claim_email;
            proxy_pass http://my_backend; # The backend site/app

            access_log /var/log/nginx/access.log main_jwt;
        }
    }

    # vim: syntax=nginx
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: frontend-conf
