apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: http-echo
  name: http-echo
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: https
      port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    app: http-echo
  type: ClusterIP
status:
  loadBalancer: {}
